### ISSUE TITLE
MHP v2.0 dataset parsing annotation images are black

### ISSUE THREAD

**Issue by MoAbd** [ZhaoJ9014/Multi-Human-Parsing_MHP#13]

**Comment by sbrugman** [comment]
On brief inspection, I can imagine why you observe the images as fully black. When taking a closer look, you can see the classes are encoded in the R-channel (red). Given the classes below we can see that some classes may be nearly imperceptable due to their low values (colors in RGB range from 0-255).

    0: Background
    1: Cap/hat
    2: Helmet
    3: Face
    4: Hair
    5: Left-arm
    6: Right-arm
    7: Left-hand
    8: Right-hand
    9: Protector
    10: Bikini/bra
    11: Jacket/windbreaker/hoodie 
    12: Tee-shirt
    13: Polo-shirt
    14: Sweater
    15: Singlet
    16: Torso-skin
    17: Pants
    18: Shorts/swim-shorts
    19: Skirt
    20: Stockings
    21: Socks
    22: Left-boot
    23: Right-boot
    24: Left-shoe
    25: Right-shoe 
    26: Left-highheel
    27: Right-highheel
    28: Left-sandal
    29: Right-sandal
    30: Left-leg
    31: Right-leg
    32: Left-foot
    33: Right-foot
    34: Coat
    35: Dress
    36: Robe
    37: Jumpsuit
    38: Other-full-body-clothes
    39: Headwear
    40: Backpack
    41: Ball
    42: Bats
    43: Belt
    44: Bottle
    45: Carrybag
    46: Cases
    47: Sunglasses
    48: Eyewear
    49: Glove
    50:Scarf
    51: Umbrella
    52: Wallet/purse
    53: Watch
    54: Wristband
    55: Tie
    56: Other-accessary
    57: Other-upper-body-clothes
    58: Other-lower-body-clothes

This script visualises the images in a way that aligns with our perception:
https://github.com/ZhaoJ9014/Multi-Human-Parsing/blob/master/Evaluation/Multi-Human-Parsing/v2/mhp_data.py
