### ISSUE TITLE
Code for Evaluation

### ISSUE THREAD

**Issue by eugenelawrence** [ZhaoJ9014/Multi-Human-Parsing_MHP#2]
Hi, @ZhaoJ9014 
The current code for multi-person parsing evaluation does not support the **PCP** metric.
I wonder will the code support PCP in the future.

**Comment by eugenelawrence** [comment]
Moreover, the code seems to only support instance-level segmentation but not support the instance-level human parsing. While the former should only separate the objects, the latter should know the instance parts come from the same objects.
@ZhaoJ9014 Can you provide a correct evaluation code for the MHP v2.0 dataset?

**Comment by ZhaoJ9014** [comment]
Dear Lawrence,


Thank you for your email. I am on travel currently, sorry for the late reply.


Actually, the answers to your questions and more details have already included in our MHP v2.0 paper (https://arxiv.org/pdf/1804.03287.pdf), MHP v1.0 paper (https://arxiv.org/pdf/1705.07206.pdf), MHP github page (https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP) and MHP project page (https://lv-mhp.github.io<https://lv-mhp.github.io/>). We briefly list the answers as follows for your convenience.


We use the Average Precision based on part (AP^p) and Percentage of Correctly parsed semantic Parts (PCP) metrics for multi-human parsing evaluation. Additionally, we also report the AP^p_{vol}, which is the mean of the AP^p at IoU thresholds ranging from 0.1 to 0.9, in increments of 0.1. We have provided the official evaluation code via https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP. In particular, given the prediction and corresponding ground truth, the file eval_mhp.py computes the AP^p@IoU=0.5, PCP@IoU=0.5. For AP^p_{vol}, you can simply set the IoU threshold "ovthresh_seg"=0.1 to 0.9 each time and then compute the mean value.

Hope this helps. If you have further concerns or questions, please feel free to drop us an email.

Thank you and best regards.

Yours sincerely,

ZHAO Jian

---------------------------------------------
ZHAO Jian :: http://zhaoj9014.github.io<http://zhaoj9014.github.io/>
Ph.D. candidate, Learning and Vision Group
Department of Electrical and Computer Engineering
Faculty of Engineering
National University of Singapore
Vision and Machine Learning Lab, E4-#08-24, 4 Engineering Drive 3, National University of Singapore, Singapore 117583
Tel: (65) 9610 7176
Email: zhaojian90@u.nus.edu

________________________________
发件人: Lawrence <notifications@github.com>
发送时间: 2018年4月18日 19:22
收件人: ZhaoJ9014/Multi-Human-Parsing_MHP
抄送: Zhao Jian; Mention
主题: Re: [ZhaoJ9014/Multi-Human-Parsing_MHP] Code for Evaluation (#2)


Moreover, the code seems to only support instance-level segmentation but not support the instance-level human parsing. While the former should only separate the objects, the latter should know the instance parts come from the same objects.
@ZhaoJ9014<https://github.com/ZhaoJ9014> Can you provide a correct evaluation code for the MHP v2.0 dataset?

―

**Comment by eugenelawrence** [comment]
@ZhaoJ9014 Thanks for your reply.
I have read your evaluation code, but the code is not the same as the papers.

There are mainly two differences in all.
1. The PCP is always zero as shown in [eval_mhp.py#L140](https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP/blob/master/Evaluation/Multi-Human-Parsing/eval_mhp.py#L140).
2. The detection boxes are extracted from the ground-truth rather than the prediction, as shown in [eval_mhp.py#L147](https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP/blob/master/Evaluation/Multi-Human-Parsing/eval_mhp.py#L147).

Please correct me if I'm wrong here.

**Comment by ZhaoJ9014** [comment]
Dear Lawrence,


Thank you for your email.


Our evaluation is actually strictly consistent with our papers Experiments -- Evaluation Metrics. For your concerns, please refer to the Readme file and then run our code with your predictions, since other participants of our MHP challenges have already tested with the same code without errors based on their feedback.

Thank you and best regards.

Yours sincerely,

ZHAO Jian

---------------------------------------------
ZHAO Jian :: http://zhaoj9014.github.io<http://zhaoj9014.github.io/>
Ph.D. candidate, Learning and Vision Group
Department of Electrical and Computer Engineering
Faculty of Engineering
National University of Singapore
Vision and Machine Learning Lab, E4-#08-24, 4 Engineering Drive 3, National University of Singapore, Singapore 117583
Tel: (65) 9610 7176
Email: zhaojian90@u.nus.edu

________________________________
发件人: Lawrence <notifications@github.com>
发送时间: 2018年4月21日 13:02
收件人: ZhaoJ9014/Multi-Human-Parsing_MHP
抄送: Zhao Jian; Mention
主题: Re: [ZhaoJ9014/Multi-Human-Parsing_MHP] Code for Evaluation (#2)


@ZhaoJ9014<https://github.com/ZhaoJ9014> Thanks for your reply.
I have read your evaluation code, but the code is not the same as the papers.

There are mainly two differences in all.

  1.  The PCP is always zeros as shown in eval_mhp.py#L140<https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP/blob/master/Evaluation/Multi-Human-Parsing/eval_mhp.py#L140>.
  2.  The detection boxes are extracted from the ground-truth rather than the prediction, as shown in eval_mhp.py#L147<https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP/blob/master/Evaluation/Multi-Human-Parsing/eval_mhp.py#L147>.

Please correct me if I'm wrong here.

―

**Comment by eugenelawrence** [comment]
Finally, I figure out the problems. I have made some mistakes.
Your code for evaluation is suitable for the MHP v1.0 dataset since it only contains 4,980 images totally. 
While I try to use it on MHP v2.0, the mistake happens.
Furthermore, the evaluation code should contain a folder named 'global_tag', which is required in MHP v2.0.
Though I have modified the code to suit for MHP v2.0, I think you should update the code to v2.0.

Best.

**Comment by ZhaoJ9014** [comment]
Hi,

Thank you very much for your feedback and suggestion, we will revise accordingly.

Best.

Yours,

ZHAO Jian

发自我的 iPhone

在 2018年4月22日，18:12，Lawrence <notifications@github.com<mailto:notifications@github.com>> 写道：


Finally, I figure out the problems. I have made some mistakes.
Your code for evaluation is suitable for the MHP v1.0 dataset since it only contains 4,980 images totally.
While I try to use it on MHP v2.0, the mistake happens.
Furthermore, the evaluation code should contain a folder named 'global_tag', which is required in MHP v2.0.
Though I have modified the code to suit for MHP v2.0, I think you should update the code to v2.0.

Best.
